SaaS-ify the Database Schema
redhat-et/apex pull request #345
Opened 2023-01-26 19:57 UTC by dave-tucker

Based on discussions last week we wanted to:
1. Rename Zone to Organization
2. Remove Peers and collapse into Device
3. For every User we see, create a dedicated Organization for them
4. (If feature-flag enabled) Allow creation of New Organizations
5. (Not implemented) Allow user to join another Organization
6. (Not implemented) If a User is a member of multiple organizations, they must configure which org they want their devices onboarded to. Default will be their own Org.

Issue #348 

Signed-off-by: Dave Tucker <dave@dtucker.co.uk>

2023-02-09 00:24 UTC, russellb requested changes
To recap our conversation via chat, I'd like to get a design doc in `docs/design/` that covers the plan for this schema change. If this is phase 1 of a multi-phase effort, it would be great to get that mapped out to ensure everyone is on the same page. It would be easiest to do that in another PR so we can iterate and merge it separately and ahead of this one. Thanks!

2023-02-09 17:05 UTC, dave-tucker commented
Design doc is in #396

2023-02-09 18:11 UTC, nerdalert approved these changes
Im ok with the yolo breakage. Flipping the default org to a hub-zone should funnel the agent into requiring a discovery/relay node.

2023-02-09 18:11 UTC, nerdalert commented on internal/handlers/organization.go
> +		HubZone:     request.HubZone,
Default to hub zone true. :exploding_head:
```
HubZone:     true,
```

2023-02-16 21:39 UTC, dave-tucker commented
![](https://media.giphy.com/media/FuvVKU8Jxq1CE/giphy.gif)

2023-02-16 22:04 UTC, merged