clean up: reduce code duplication in stun.go, use a dynamic port the wg interface that we can open.
redhat-et/apex pull request #422
Opened 2023-02-15 16:40 UTC by chirino

Using a random high port for the wg is not guaranteed to not be in use by another process, so lets ask the OS for a dynamic port instead.

This now avoids an additional stun request once we have determined that the device is behind a symmetric nat.

Wait for apex to be deployed when running `make recreate-db`

2023-02-15 20:49 UTC, nerdalert requested changes
Looks good @chirino, ty! Just one issue is flipping the stun results evaluation. If the results don't match we infer it is behind a symmetric NAT cone somewhere in the path.

2023-02-15 20:49 UTC, nerdalert commented on internal/apex/apex.go
> +		isSymmetric = stunAddr.String() == stunAddr2.String()
```suggestion
		isSymmetric = stunAddr.String() != stunAddr2.String()
```

2023-02-16 07:19 UTC, vishnoianil commented on internal/apex/stun.go
> +	stunServer  = "stun.l.google.com:19302"
if we use stunServer1 in utils.go, we can probably get rid of one of the stun server here?

2023-02-16 14:06 UTC, chirino commented on internal/apex/apex.go
> +		isSymmetric = stunAddr.String() == stunAddr2.String()
doh.. good catch.  thx.

2023-02-16 15:44 UTC, merged