Add .vscode/settings.json to gitignore
redhat-et/apex pull request #427
Opened 2023-02-16 16:48 UTC by vishnoianil

So that *.md only patches with settings.json changes won't trigger build jobs.

2023-02-16 16:52 UTC, russellb requested changes
If you add it to gitignore, you should remove the file from the tree, too.

2023-02-16 17:02 UTC, vishnoianil commented
> If you add it to gitignore, you should remove the file from the tree, too.

Yeah, I was thinking of removing the file as well, but it might remove the local .vscode/settings.json from the local dev environment as well, whenever anyone will pull the main? so just out of caution i kept it, but happy to toss it if that's okay.

2023-02-16 18:09 UTC, russellb commented
I don’t think it will remove it if you have any local changes to the file. 

What’s the harm in keeping it, though? On slack you said you didn’t want it triggering build jobs, right? You could just ignore it in that config?

2023-02-16 18:50 UTC, vishnoianil commented
> I don’t think it will remove it if you have any local changes to the file.
> 
> What’s the harm in keeping it, though? On slack you said you didn’t want it triggering build jobs, right? You could just ignore it in that config?

Yeah, we can do that as well. (Also i prefer setting.json to be in the repo, so you don't have to deal with those annoying dictionary warning).

2023-02-17 01:29 UTC, russellb commented
> > I don’t think it will remove it if you have any local changes to the file.
> > What’s the harm in keeping it, though? On slack you said you didn’t want it triggering build jobs, right? You could just ignore it in that config?
> 
> Yeah, we can do that as well. (Also i prefer setting.json to be in the repo, so you don't have to deal with those annoying dictionary warning).

I use vscode, too. I appreciate your updates. Let's leave it and just fix CI.

2023-02-17 20:34 UTC, vishnoianil commented
> > > I don’t think it will remove it if you have any local changes to the file.
> > > What’s the harm in keeping it, though? On slack you said you didn’t want it triggering build jobs, right? You could just ignore it in that config?
> > 
> > 
> > Yeah, we can do that as well. (Also i prefer setting.json to be in the repo, so you don't have to deal with those annoying dictionary warning).
> 
> I use vscode, too. I appreciate your updates. Let's leave it and just fix CI.

Done

2023-02-18 01:27 UTC, vishnoianil commented
@russellb Integration test is failing, but rest of the jobs are passing, so probably for this PR, we don't have to wait for e2e to pass?

2023-02-19 01:50 UTC, russellb approved these changes

2023-02-19 01:50 UTC, merged